version: '3.9'
services:
  website-client:
    container_name: ipocircle-client
    init: true
    build: 
      context: .
    restart: 'always'
    ports:
      - 3000:3000
    env_file:
      - .env.dockerBuild