version: '3.9'
services:
  website-client:
    container_name: ipocircle-client
    init: true
    build: 
      context: .
    restart: 'always'
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL="https://api.ipocircle.com/api/v1"