version: '3.9'
services:
  trading-desk-client:
    container_name: vn-creditcard-client
    init: true
    build: 
      context: .
    restart: 'always'
    ports:
      - 3000:3000
    env_file:
      - .env.dev
      - .env.prod