export { default as Blog } from './blog.svg'
export { default as Data } from './data.svg'
export { default as Customize } from './cutomize.svg'
export { default as Analysis } from './analysis.svg'
export { default as Dashboard } from './dashboard.png'
