export { default as LogoSample } from './logosample.png'
export { default as Logo1 } from './logo1.png'
export { default as Logo2 } from './logo2.svg'
export { default as Logo3 } from './logo3.svg'
export { default as Logo4 } from './logo4.png'
export { default as Logo5 } from './logo5.png'
export { default as Logo6 } from './logo6.png'
