import { ContentType } from '@/app/ipo/data.types'

export default async function sanitizeIpoDetailsData(content: any) {
  const formattedData: ContentType = {
    CompanyDetailsData: {
      company_logo_url: content.data[0].logo_url || '',
      company_name: content.data[0].name,
      opening_date: content.data[0].opening_date || '---',
      closing_date: content.data[0].closing_date || '---',
      description: content.data[0].description || '',
    },
    IpoDetailsData: {
      ipo_date: content.data[0].listing_date || '',
      face_value: content.data[0].face_value || 0,
      price_band: content.data[0].priceband || 0,
      lot_size_retails: content.data[0].shares_in_lot || 0,
      total_size: content.data[0].total_issue || 0,
      fresh_issue: content.data[0].fresh_issue || 0,
      ofs: content.data[0].ofs || '',
      issue_type: content.data[0].issue_type || '',
      listing_at: content.data[0].listing_at || [],
    },
    IpoTimetableData: {
      open_date: content.data[0].opening_date || '---',
      close_date: content.data[0].closing_date || '---',
      allotment_date: content.data[0].allotment_date || '',
      initiation_of_refunds: content.data[0].init_refunds || '',
      credit_of: content.data[0].credit_of || '',
      listing_date: content.data[0].listing_date || '---',
      cutoff: content.data[0].cutoffmandate || '',
      time_upf: content.data[0].time_upf || '',
    },
    LotSizeData: {
      min_retail: content.data[0].min_retail || 0,
      max_retail: content.data[0].max_retail || 0,
      min_shni: content.data[0].min_shni || 0,
      max_shni: content.data[0].max_shni || 0,
      min_bhni: content.data[0].min_bhni || 0,
      max_bhni: content.data[0].max_bhni || 0,
    },
    PerformanceData: {
      market_cap: content.data[0].market_cap || 0,
      roe: content.data[0].roe || 0,
      roce: content.data[0].roce || 0,
      debt: content.data[0].debt || 0,
      eps: content.data[0].eps || 0,
      ronw: content.data[0].ronw || 0,
    },
    CompanyFinancialsData: {
      // completely missing
      period1: {
        date: content.data[0].period || '',
        assets: content.data[0].assets || 0,
        revenue: content.data[0].revenue || 0,
        profits_after_tax: content.data[0].profit_after_tax || 0,
        networth: content.data[0].net_worth || 0,
        reserves_and_surplus: content.data[0].reserves || 0,
        total_borrowings: content.data[0].borrowing || 0,
      },
      period2: {
        date: content.data[0].period || '',
        assets: content.data[0].assets || 0,
        revenue: content.data[0].revenue || 0,
        profits_after_tax: content.data[0].profit_after_tax || 0,
        networth: content.data[0].net_worth || 0,
        reserves_and_surplus: content.data[0].reserves || 0,
        total_borrowings: content.data[0].borrowing || 0,
      },
      period3: {
        date: content.data[0].period || '',
        assets: content.data[0].assets || 0,
        revenue: content.data[0].revenue || 0,
        profits_after_tax: content.data[0].profit_after_tax || 0,
        networth: content.data[0].net_worth || 0,
        reserves_and_surplus: content.data[0].reserves || 0,
        total_borrowings: content.data[0].borrowing || 0,
      },
      period4: {
        date: content.data[0].period || '',
        assets: content.data[0].assets || 0,
        revenue: content.data[0].revenue || 0,
        profits_after_tax: content.data[0].profit_after_tax || 0,
        networth: content.data[0].net_worth || 0,
        reserves_and_surplus: content.data[0].reserves || 0,
        total_borrowings: content.data[0].borrowing || 0,
      },
      period5: {
        date: content.data[0].period || '',
        assets: content.data[0].assets || 0,
        revenue: content.data[0].revenue || 0,
        profits_after_tax: content.data[0].profit_after_tax || 0,
        networth: content.data[0].net_worth || 0,
        reserves_and_surplus: content.data[0].reserves || 0,
        total_borrowings: content.data[0].borrowing || 0,
      },
    },
    SubscriptionsData: {
      qib: content.data[0].qib || '',
      nii_snii: content.data[0].nii_snii || 0,
      nii_bnii: content.data[0].nii_bnii || 0,
      retail: content.data[0].retail || 0,
    },
    DataPanelData: {
      IpoDetailsData: {
        ipo_date: content.data[0].listing_date || '',
        face_value: content.data[0].face_value || 0,
        price_band: content.data[0].priceband || 0,
        lot_size_retails: content.data[0].shares_in_lot || 0,
        total_size: content.data[0].total_issue || 0,
        fresh_issue: content.data[0].fresh_issue || 0,
        ofs: content.data[0].ofs || '',
        issue_type: content.data[0].issue_type || '',
        listing_at: content.data[0].listing_at || [],
      },
      IpoTimetableData: {
        open_date: content.data[0].opening_date || '---',
        close_date: content.data[0].closing_date || '---',
        allotment_date: content.data[0].allotment_date || '---',
        initiation_of_refunds: content.data[0].init_refunds || '',
        credit_of: content.data[0].credit_of || '',
        listing_date: content.data[0].listing_date || '---',
        cutoff: content.data[0].cutoffmandate || '',
        time_upf: content.data[0].time_upf || '',
      },
      LotSizeData: {
        min_retail: content.data[0].min_retail || 0,
        max_retail: content.data[0].max_retail || 0,
        min_shni: content.data[0].min_shni || 0,
        max_shni: content.data[0].max_shni || 0,
        min_bhni: content.data[0].min_bhni || 0,
        max_bhni: content.data[0].max_bhni || 0,
      },
      PerformanceData: {
        market_cap: content.data[0].market_cap || 0,
        roe: content.data[0].roe || 0,
        roce: content.data[0].roce || 0,
        debt: content.data[0].debt || 0,
        eps: content.data[0].eps || 0,
        ronw: content.data[0].ronw || 0,
      },
      CompanyFinancialsData: {
        period1: {
          date: content.data[0].period || '',
          assets: content.data[0].assets || 0,
          revenue: content.data[0].revenue || 0,
          profits_after_tax: content.data[0].profit_after_tax || 0,
          networth: content.data[0].net_worth || 0,
          reserves_and_surplus: content.data[0].reserves || 0,
          total_borrowings: content.data[0].borrowing || 0,
        },
        period2: {
          date: content.data[0].period || '',
          assets: content.data[0].assets || 0,
          revenue: content.data[0].revenue || 0,
          profits_after_tax: content.data[0].profit_after_tax || 0,
          networth: content.data[0].net_worth || 0,
          reserves_and_surplus: content.data[0].reserves || 0,
          total_borrowings: content.data[0].borrowing || 0,
        },
        period3: {
          date: content.data[0].period || '',
          assets: content.data[0].assets || 0,
          revenue: content.data[0].revenue || 0,
          profits_after_tax: content.data[0].profit_after_tax || 0,
          networth: content.data[0].net_worth || 0,
          reserves_and_surplus: content.data[0].reserves || 0,
          total_borrowings: content.data[0].borrowing || 0,
        },
        period4: {
          date: content.data[0].period || '',
          assets: content.data[0].assets || 0,
          revenue: content.data[0].revenue || 0,
          profits_after_tax: content.data[0].profit_after_tax || 0,
          networth: content.data[0].net_worth || 0,
          reserves_and_surplus: content.data[0].reserves || 0,
          total_borrowings: content.data[0].borrowing || 0,
        },
        period5: {
          date: content.data[0].period || '',
          assets: content.data[0].assets || 0,
          revenue: content.data[0].revenue || 0,
          profits_after_tax: content.data[0].profit_after_tax || 0,
          networth: content.data[0].net_worth || 0,
          reserves_and_surplus: content.data[0].reserves || 0,
          total_borrowings: content.data[0].borrowing || 0,
        },
      },
      SubscriptionsData: {
        qib: content.data[0].qib || '',
        nii_snii: content.data[0].nii_snii || 0,
        nii_bnii: content.data[0].nii_bnii || 0,
        retail: content.data[0].retail || 0,
      },
    },
    AnchorDetailsData: {
      bid_date: content.data[0].anchor_bid_date || '',
      shares_offerred: content.data[0].anchor_shares_offerred || 0,
      portion_size: content.data[0].anchor_portion || 0,
      anchorLockIn_50per_30days: content.data[0].anchor_lockin_half || 0,
      anchorLockIn_50per_90days: content.data[0].anchor_lockin_rest || 0,
    },
    IppoReservationData: {
      qib_shares_offerred: 0,
      nil_shares_offerred: 0,
      retail_shares_offerred: 0,
    },
    PromoterHoldingsData: {
      preissue_share_holdings: content.data[0].promoter_holding_pre || 0,
      postissue_share_holdings: content.data[0].promoter_holding_post || 0,
    },
    ObjectIssueData: {
      text: content.data[0].objectIssueData,
    },
    CompanyContactData: {
      name: content.data[0].name || '',
      address: content.data[0].company_address || '',
      phone: content.data[0].company_phone || '',
      email: content.data[0].company_email || '',
      website: content.data[0].company_website || '',
    },
    RegistrarContactData: {
      name: content.data[0].registrar_name || '',
      address: content.data[0].registrar_address || '',
      phone: content.data[0].registrar_phone || '',
      email: content.data[0].registrar_email || '',
      website: content.data[0].registrar_website || '',
    },
    DocumentsData: {
      rhp: content.data[0].rhp || '',
      drhp: content.data[0].drhp || '',
    },
    ReviewData: {
      review: '',
    },
    GmpData: content.data[0].gmpData || [],
  }

  return formattedData
}
