name: Next App CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: |
          ls -al /home/runner/work/website-client/website-client/package.json
          npm install
      - name: Running tests
        run: npm test
      - name: Building App
        run: npm run build